services:
  app:
      image: fastapi:latest
      container_name: fastapi_app
      ports:
        - "5000:5000"
      environment:
        - DB_HOST=mysql
        - DB_USER=${MYSQL_USER}
        - DB_PASSWORD=${MYSQL_PASSWORD}
        - DB_NAME=${MYSQL_DATABASE}
      depends_on:
        - mysql
      restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_HOST="%"
    ports:
      - "3306:3306"
    networks:
      backend:
        ipv4_address: 172.20.0.10
    restart: unless-stopped

  haproxy:
    image: haproxy:2.8
    container_name: haproxy_proxy
    volumes:
      - ./haproxy/reverse/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - "8080:8080"
    depends_on:
      - app
    networks:
      proxy-frontend:
      proxy-backend:
      backend:
    restart: unless-stopped

  web:
    image: nginx:alpine
    container_name: web
    volumes:
      - ./nginx/ingress/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8090:80"
    networks:
      backend:
        ipv4_address: 172.20.0.5
      proxy-frontend:
      proxy-backend:
    depends_on:
      - haproxy
    restart: unless-stopped

networks:
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
  proxy-backend:
    driver: bridge
  proxy-frontend:
    driver: bridge
volumes:
  mysql_data: