FROM python:3.12-slim
WORKDIR /app
COPY . .
RUN apt-get update && apt-get install uvicorn -y
RUN apt-get install -y gcc default-libmysqlclient-dev pkg-config && \
    rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir -r requirements.txt
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"]
